### PR TITLE
Add example to documentation

### LINKED ISSUE #124: Add example(s)
We need to add usage example(s).

### PR DESCRIPTION
**Pull request by CasperWA**
Closes #124 

Adds an example through a Jupyter Notebook.
The notebook is rendered nicely through [mkdocs-jupyter](https://github.com/danielfrg/mkdocs-jupyter).

To inspect the proper rendition of the notebook, please follow these steps:

1. Clone repository (if not done already).

   ```shell
   git clone https://github.com/SINTEF/oteapi-optimade.git
   cd oteapi-optimade
   ```

2. Checkout this PR's branch and install all dependencies.

   ```shell
   git fetch --all -tp
   git checkout cwa/close-124-examples
   pip install -U pip setuptools wheel flit
   pip install -U -e .[docs]
   ```

3. Execute the local MkDocs server:

   ```shell
   mkdocs serve
   ```

The local URL should be written to the console at the end of building the documentation and starting the server.
Then through the menu on the left, one can navigate through "Examples" to "Use OTEAPI-OPTIMADE with OTElib".

It should look something like this:
image

### CODE REVIEW

**Comment by jesper-friis** [comment]
Please add `mkdocs-jupyter` to the requirements. Otherwise you can't start the mkdocs server

**Comment by jesper-friis** [comment]
In the documentation example, it would be good to include the commands for starting the oteapi services instead of just referring to external documentation. Only one way to start the services needs to be shown here. It is fine to refer to oteapi-services for other options.

**Comment by CasperWA** [comment]
> Please add `mkdocs-jupyter` to the requirements. Otherwise you can't start the mkdocs server

I did. Just fixed it. Also, if following the instructions above (installing with the `docs` extra) it shouldn't be an issue. It was only an issue in the CI/CD workflow, since it uses the `dev` extra. This is what I fixed.
Are you sure you have checked out the correct branch?

**Comment by CasperWA** [comment]
> In the documentation example, it would be good to include the commands for starting the oteapi services instead of just referring to external documentation. Only one way to start the services needs to be shown here. It is fine to refer to oteapi-services for other options.

I'd rather not reiterate too much external documentation, since if the external documentation changes, this one will be outdated and unusable for something that does not have anything directly to do with this repository/plugin.

**Comment by jesper-friis** [comment]
> I suppose the middle ground would be to say something like "at the time of writing (15.05.2023) the instructions are..."?

That is fine. I guess the instruction should be along the line of checking out oteapi-services and do

    docker-compose pull
    docker-compose up -d

**Comment by jesper-friis** [comment]
Please update the below figure. The filter strategy should come after the data resource strategy in the pipeline: 

image

This is conceptually important. We have the partial pipeline documenting the data source (typically `DataResource >> Parse >> Mapping`). That should be treated as one unit and always come first in the pipeline. The filter is not a part of the documentation of the data resource, but is a part of our application that selects the subset of all the data in the data resource we are interested in. It should use the `initialize()` method to specify the query such that only the information we need is fetched from the data resource.

**Comment by jesper-friis** [comment]
I am trying to follow the example in `docs/examples/index.md`

```python
pipeline = filter_strategy >> data_resource_strategy
session = pipeline.get()
```
raises 

```python
ApiError: APIError: status=500 Cannot initialize data resource: session_id='session-2f0c89e9-d691-43ed-a1c2-20593345c310' resource_id='dataresource-a3a4bde7-2611-4b1f-a450-8038048a797a'
```
when calling `pipeline.get()`. There is unfortunately noe clue about what went wrong. With this not working, it is difficult for me to check the rest of the example. Does it work for you?

**A side question**: Is the session really returned by the get method? Since it is just a (preferable small) json payload that is anyway transferred between the microservices, it certainly possible to return it. I also think it make sense, but I understood from Thomas that he was against that. Has he changed his mind?

**A second side node**: We should add an issue in oteapi-services that the full traceback and error message from uncaught exceptions should be included in the response. otelib should be updated to show these error messages. That would make debugging much easier. Maybe such detailed error messages could be seen as a security issue, since they could be used by an attacker to probe the underlying services. If that is considered an issue, the detailed error message could still be made available for privileged users/developers.

**Comment by jesper-friis** [comment]
By the way, `docker logs` gave some hints. Seems that I should run docker with the correct directory mounted. It would be great if you could add instructions about how do start docker in the right way for the example to work...

```
No extra plugin packages provided. Specify 'OTEAPI_PLUGIN_PACKAGES' to specify plugin packages.
[2023-05-15 15:57:40 +0000] [15] [INFO] Running on http://0.0.0.0:8080 (CTRL + C to quit)
[2023-05-15 16:14:10 +0000] [15] [ERROR] Error in ASGI Framework
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/hypercorn/asyncio/task_group.py", line 23, in _handle
    await app(scope, receive, send, sync_spawn, call_soon)
  File "/usr/local/lib/python3.9/site-packages/hypercorn/app_wrappers.py", line 33, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/app/routers/dataresource.py", line 194, in initialize_dataresource
    session_update = create_strategy("resource", config).initialize(
  File "/usr/local/lib/python3.9/site-packages/oteapi/plugins/factories.py", line 183, in create_strategy
    return StrategyFactory.make_strategy(config, strategy_type)
  File "/usr/local/lib/python3.9/site-packages/oteapi/plugins/factories.py", line 92, in make_strategy
    raise NotImplementedError(
NotImplementedError: The resource strategy 'OPTIMADE' does not exist.
```

**Comment by jesper-friis** [comment]
I of cause get the same error message when I try to run the Jupyter notebook in `docs/examples/otelib.ipynb`.

Please add `pip install notebook` to the setup instructions.

**Comment by jesper-friis** [comment]
Repeating the same example twice it quite boring. Can you split it up into two sub-pages, one for each otelib backend.

**Comment by jesper-friis** [comment]
The example should be run at a part of the CI testing.

**Comment by CasperWA** [comment]
> Please update the below figure. The filter strategy should come after the data resource strategy in the pipeline:
> 
> image
> 
> This is conceptually important. We have the partial pipeline documenting the data source (typically `DataResource >> Parse >> Mapping`). That should be treated as one unit and always come first in the pipeline. The filter is not a part of the documentation of the data resource, but is a part of our application that selects the subset of all the data in the data resource we are interested in. It should use the `initialize()` method to specify the query such that only the information we need is fetched from the data resource.

I did this originally, but unfortunately the `session` object is not returned correctly from the "filter strategy", so I had to switch them around. I believe this issue is being resolved in OTElib, but this is an issue.
Furthermore, retrieving the data from the `session` object is plain wrong and should not be done like this. But that's out-of-scope of this tutorial to fix.

**Comment by CasperWA** [comment]
> By the way, `docker logs` gave some hints. Seems that I should run docker with the correct directory mounted. It would be great if you could add instructions about how do start docker in the right way for the example to work...
> 
> ```
> No extra plugin packages provided. Specify 'OTEAPI_PLUGIN_PACKAGES' to specify plugin packages.
> [2023-05-15 15:57:40 +0000] [15] [INFO] Running on http://0.0.0.0:8080 (CTRL + C to quit)
> [2023-05-15 16:14:10 +0000] [15] [ERROR] Error in ASGI Framework
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/hypercorn/asyncio/task_group.py", line 23, in _handle
>     await app(scope, receive, send, sync_spawn, call_soon)
>   File "/usr/local/lib/python3.9/site-packages/hypercorn/app_wrappers.py", line 33, in __call__
>     await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 276, in __call__
>     await super().__call__(scope, receive, send)
>   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
>     raise exc
>   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
>     await self.app(scope, receive, _send)
>   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
>     raise exc
>   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
>     await self.app(scope, receive, sender)
>   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
>     raise e
>   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
>     await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
>     await route.handle(scope, receive, send)
>   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
>     await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
>     response = await func(request)
>   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 237, in app
>     raw_response = await run_endpoint_function(
>   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
>     return await dependant.call(**values)
>   File "/app/app/routers/dataresource.py", line 194, in initialize_dataresource
>     session_update = create_strategy("resource", config).initialize(
>   File "/usr/local/lib/python3.9/site-packages/oteapi/plugins/factories.py", line 183, in create_strategy
>     return StrategyFactory.make_strategy(config, strategy_type)
>   File "/usr/local/lib/python3.9/site-packages/oteapi/plugins/factories.py", line 92, in make_strategy
>     raise NotImplementedError(
> NotImplementedError: The resource strategy 'OPTIMADE' does not exist.
> ```

Concerning this comment and the previous one.
You need to of course reference this repository in the `OTEAPI_PLUGIN_PACKAGES` variable to install the plugin. The error message is quite clear: `The resource strategy "OPTIMADE" does not exist`, meaning it is not installed...

**Comment by CasperWA** [comment]
> I am trying to follow the example in `docs/examples/index.md`
> 
> ```python
> pipeline = filter_strategy >> data_resource_strategy
> session = pipeline.get()
> ```
> 
> raises
> 
> ```python
> ApiError: APIError: status=500 Cannot initialize data resource: session_id='session-2f0c89e9-d691-43ed-a1c2-20593345c310' resource_id='dataresource-a3a4bde7-2611-4b1f-a450-8038048a797a'
> ```
> 
> when calling `pipeline.get()`. There is unfortunately noe clue about what went wrong. With this not working, it is difficult for me to check the rest of the example. Does it work for you?

You need to install the plugin when running the server...

> **A side question**: Is the session really returned by the get method? Since it is just a (preferable small) json payload that is anyway transferred between the microservices, it certainly possible to return it. I also think it make sense, but I understood from Thomas that he was against that. Has he changed his mind?

This is indeed not the way to work with this, but the only way I know how to at this point in time as there is no endpoint in the service to share files with a client.

> **A second side node**: We should add an issue in oteapi-services that the full traceback and error message from uncaught exceptions should be included in the response. otelib should be updated to show these error messages. That would make debugging much easier. Maybe such detailed error messages could be seen as a security issue, since they could be used by an attacker to probe the underlying services. If that is considered an issue, the detailed error message could still be made available for privileged users/developers.

No. A server should **_never_** reveal its internals. Any internal error messages can be picked up there: Internally. As you also experienced from the docker logs.

**Comment by CasperWA** [comment]
> Repeating the same example twice it quite boring. Can you split it up into two sub-pages, one for each otelib backend.

Yes and no. As this was a quick'n'dirty example, I didn't have capacity to come up with a more exciting example. Furthermore, it shows that there is no (or should be no) difference between the two methods, other than added information.

**Comment by CasperWA** [comment]
> The example should be run at a part of the CI testing.

This repository already has an end-2-end test that does exactly this. No need to also run the tutorial.
That said, the `mkdocs-jupyter` plugin allows for executing the notebooks upon building the documentation, hence this could act as a CI test for whether the notebook works or not.
However, since a separate server is required and the notebook references `localhost:80` it might be quite tricky to make it work properly. Hence, I'd consider it out-of-scope for this PR and writing this example, but definitely worth further investigation down the road.

**Comment by CasperWA** [comment]
> > I suppose the middle ground would be to say something like "at the time of writing (15.05.2023) the instructions are..."?
> 
> That is fine. I guess the instruction should be along the line of checking out oteapi-services and do
> 
> ```
> docker-compose pull
> docker-compose up -d
> ```

I'll come up with something. I don't think `git clone`-ing another repository is the way to go, since the same thing can be achieved by just downloading (or recreating) the docker compose file.

**Comment by CasperWA** [comment]
> > Please update the below figure. The filter strategy should come after the data resource strategy in the pipeline:
> > image
> > This is conceptually important. We have the partial pipeline documenting the data source (typically `DataResource >> Parse >> Mapping`). That should be treated as one unit and always come first in the pipeline. The filter is not a part of the documentation of the data resource, but is a part of our application that selects the subset of all the data in the data resource we are interested in. It should use the `initialize()` method to specify the query such that only the information we need is fetched from the data resource.
> 
> I did this originally, but unfortunately the `session` object is not returned correctly from the "filter strategy", so I had to switch them around. I believe this issue is being resolved in OTElib, but this is an issue. Furthermore, retrieving the data from the `session` object is plain wrong and should not be done like this. But that's out-of-scope of this tutorial to fix.

With respect to this "issue", what should the solution be? Switch it up but then not be able to switch up the code to match or keep it as is with the knowledge that it should be possible to run the pipeline either way around the strategies are placed?

**Comment by CasperWA** [comment]
Will merge this now, opening issues where necessary to follow-up. While the issues mentioned by @jesper-friis here are valid, most have been remedied.
The most crucial I see, is the way the pipeline session is (mis)handled as well as how the pipeline setup does not match with the intended way of setting up the specific strategies.

**Pull request merged**
